### ISSUE TITLE
Possible issue with keyboard events queueing

### ISSUE THREAD

**Issue by smith-j-travis** [smith-j-travis/Launcher#9]
If you hold down a key for a long time and then release, it hangs for a bit.

Untested, but someone reported that it may be the launcher so I am logging it here so I don't forget.

**Comment by vldrlf** [comment]
hi id like to learn to you can i?
and i have a lot of question i want send you msg how to do?? 
have you kakaotalk? or line? or facebook msn like this?

**Comment by smith-j-travis** [comment]
Hey, feel free to contact me at l1jsmitty@gmail.com if you have any questions!

**Comment by vldrlf** [comment]
wow omg~ my hero!!!!!!!!
he sent me msg haha actually im korean i surprise on you~

2016-10-03 8:26 GMT+09:00 Travis Smith <notifications@github.com>:

**Comment by vldrlf** [comment]
you are very awesome im watched your launcher.exe connector its was amezing


2016-10-03 8:33 GMT+09:00 3.0 Lineage <lineages3ep1@gmail.com>:

**Comment by vldrlf** [comment]
i will talk my story..
a few ago i started l1j mofidy i want old version i found l1j-en googlecode
link ha~^^
and english 3.0 packets add on my plaform its korea emulator
but i have some problem i cant add sprite more! just until1,880KB..
most of all i cant use ainhasad packet and coma of bless packet..
im so sad...but  i found same 3.0 packets little bit up version...it's
2009.08.20 lin.bin..
but i have some wrong.. the lin.bin is dont reversing gameguard and
sprite.pak loading..



2016-10-03 8:35 GMT+09:00 3.0 Lineage <lineages3ep1@gmail.com>:

**Comment by vldrlf** [comment]
sorry my bad english skill


2016-10-03 8:44 GMT+09:00 3.0 Lineage <lineages3ep1@gmail.com>:

**Comment by vldrlf** [comment]
so can you linbin reversing??  and can i make launcher.exe??

2016-10-03 8:44 GMT+09:00 3.0 Lineage <lineages3ep1@gmail.com>:

**Comment by vldrlf** [comment]
ah~ i did reversing my lin.bin so..
can i make launcher.exe on my lin,bin?

2016-10-03 10:44 GMT+09:00 3.0 Lineage <lineages3ep1@gmail.com>:

**Comment by vldrlf** [comment]
i mean my lin.bin kor version is can make launcher.exe??

2016-10-03 13:54 GMT+09:00 3.0 Lineage <lineages3ep1@gmail.com>:

**Comment by vldrlf** [comment]
becouse of window mode ... it's very good thing

**Comment by smith-j-travis** [comment]
Hey, sorry, I'm not sure what you're asking. But, to keep the issues area clean, can you email your question to l1jsmitty@gmail.com?

**Comment by vldrlf** [comment]
im open to the DRAGON_PEARL PACKET
// public S_Liquor(int objecId) {
// writeC(Opcodes.S_OPCODE_LIQUOR);
// writeD(objecId);
// writeC(1);
// }

public S_Liquor(int objecId, int type) {
writeC(Opcodes.S_OPCODE_LIQUOR);
writeD(objecId); // char id
writeC(type); // 1~7 Liquor 8 pearl
}

public static final int DRAGONPERL = 60;

public S_PacketBox(int subCode, int type, int time) {
writeC(Opcodes.S_OPCODE_PACKETBOX); writeC(subCode); switch (subCode) {
case DRAGONPERL:// �巡������ writeC(time); writeC(type); break;

2016-10-13 10:58 GMT+09:00 Travis Smith <notifications@github.com>:

**Comment by vans163** [comment]
@smith-j-travis @vldrlf Is asking if you can reverse engineer a korean lineages .exe to get a working 3rd party launcher.  @vldrlf Did not mention what their budget was.

**Comment by smith-j-travis** [comment]
Sorry, that isn't really my expertise. I have played a bit with the other clients, but the way the login encryption has changed has stumped me so far.

I might look into it at a later date, but until the L1J-en source moves to a newer client, it isn't really a priority.

**Comment by smith-j-travis** [comment]
With the changes to the launcher, this issue is no longer relevant.
